### ISSUE TITLE
OS X example build failed

### ISSUE THREAD

**Issue by MrRobb** [calebwin/emu#27]
Hello, I am trying the example:

```rust
#[macro_use]
extern crate em;
use em::*;

#[gpu_use]
fn main() {
    let mut x = vec![0.0; 1000];

    gpu_do!(load(x)); // move data to the GPU
    
    gpu_do!(launch()); // off-load to run on the GPU

    for i in 0..1000 {
        x[i] = x[i] * 10.0;
    }

    gpu_do!(read(x)); // move data back from the GPU
    
    println!("{:?}", x);
}
```

Here's the error.

```
   ...
   Compiling emu_macro v0.1.0
error[E0277]: the trait bound `syn::Expr: std::convert::From<quote::__rt::TokenStream>` is not satisfied
   --> /Users/mrrobb/.cargo/registry/src/github.com-1ecc6299db9ec823/emu_macro-0.1.0/src/passing.rs:337:50
    |
337 |                     let gpu_ident = quote! {gpu}.into();
    |                                                  ^^^^ the trait `std::convert::From<quote::__rt::TokenStream>` is not implemented for `syn::Expr`
    |
    = help: the following implementations were found:
              <syn::Expr as std::convert::From<syn::ExprArray>>
              <syn::Expr as std::convert::From<syn::ExprAssign>>
              <syn::Expr as std::convert::From<syn::ExprAssignOp>>
              <syn::Expr as std::convert::From<syn::ExprAsync>>
            and 35 others
    = note: required because of the requirements on the impl of `std::convert::Into<syn::Expr>` for `quote::__rt::TokenStream`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `emu_macro`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Am I doing something wrong? Thank you.

**Comment by calebwin** [comment]
Hi,

This is similar to the issue described [here on the Gitter chat](https://gitter.im/talk-about-emu/thoughts?at=5daa9335e3646f24c750b34b). The solution was updating Rust to latest version.

Let me know if that works for you!

**Comment by Micael106** [comment]
same here. what is the compatible version?

**Comment by calebwin** [comment]
I've tried compiling on Windows and Linux on Rust 1.38.0 and build has been successful.

`stable-x86_64-pc-windows-msvc unchanged - rustc 1.38.0 (625451e37 2019-09-23)`
`stable-x86_64-unknown-linux-gnu updated - rustc 1.38.0 (625451e37 2019-09-23)`

@MrRobb are you also on MacOS?

However, interestingly, when I look at [the docs](https://docs.rs/syn/1.0.5/syn/enum.Expr.html) the error message seems correct. `From<proc_macro2::TokenStream>` is implemented but not `From<quote::__rt::TokenStream>`.

I'll try to switch to `proc_macro2::TokenStream` and see if that can be done without regression when I get a chance.

**Comment by Micael106** [comment]
I tried several versions of rust and got the same error, older versions and nightly

**Comment by calebwin** [comment]
I've replicated the issue and I'm really not sure how to resolve it. Digging into [`quote` source code](https://github.com/dtolnay/quote/blob/master/src/lib.rs#L92), it seems like there is a `runtime.rs` module that makes a [`pub use proc_macro2::*`](https://github.com/dtolnay/quote/blob/master/src/runtime.rs#L5). So somehow that seems to be creating 2 copies of `proc_macro2` and that's causing type mismatch errors which the `.into()` then fails to convert into the correct type.

I don't actually have that much experience with Rust so it would be great if someone could `git clone` this, change `em/Cargo.toml`'s `emu_macro = 0.1.0` to `emu_macro = { path = "../emu_macro" }`, and try to fix the type mismatch error.

Or, if anyone has ideas for how to fix this, please let me know.

**Comment by MrRobb** [comment]
@calebwin I am using MacOS Catalina and Rust 1.38.0.

**Comment by Micael106** [comment]
unfortunately I also know very little about rust to help solve, I started learning this week for a college GPU job. I will use version 0.2.0, which compiled here.

This version uses quote 0.6.13

**Comment by calebwin** [comment]
@MrRobb @Micael106 I think I fixed the issue; the fix is pushed to [the dev branch](https://github.com/calebwin/emu/tree/dev).

Would you mind cloning it and testing it out? If it works fine, I will probably pull it into the master branch and then publish the fix.

**Comment by Micael106** [comment]
it's working now. thank you!
![Screen Shot 2019-11-02 at 22 38 09](https://user-images.githubusercontent.com/13973988/68079063-dd033080-fdc1-11e9-97f8-106206787e4c.png)

**Comment by calebwin** [comment]
Yay! I'll pull into master and publish an update.

**Comment by jkelleyrtp** [comment]
Not sure if you've had a chance to pull it in yet, just reporting in that the dev branch works but not master for me

**Comment by calebwin** [comment]
Yeah. The dev branch works but not the master. I haven't pulled in dev yet.
