### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by PerfectStepCoder** [calebwin/emu#36]
Hi everyone! This project ia awesome. I was tring run example code, but I got error: 
let gpu_ident = quote! {gpu}.into(); -> 
                                               ^^^^ the trait `std::convert::From<quote::__private::TokenStream>` is not implemented for `syn::Expr`
this error was in passing.rs file. 
Help me please to understand how it works?
p.s. my OS is Windows 10 64 bit, Rust has 1.42.0 version, and I have installed OpenCL driver (my video card is Nvidia GeForce 1070).

**Comment by calebwin** [comment]
If you use the `dev` branch, that issue should go away.

With that said, that is a version of Emu that I'm not developing as of now. I'm currently developing a lower-level version that is in the `emu_core` folder. I'll be releasing a crate and documentation for that later this afternoon.

**Comment by PerfectStepCoder** [comment]
Thanks for anwer. I will wait for your release.

**Comment by calebwin** [comment]
The new version is released. Docs are [here](https://calebwin.github.io/emu) and crate [here](https://crates.io/crates/emu_core).

Let me know what you think!

**Comment by PerfectStepCoder** [comment]
I think it is a good job! So, I am trying to start examle, bu I got error while compiling:
![image](https://user-images.githubusercontent.com/23447745/79061936-0b086d00-7c9e-11ea-9355-e600e6723325.png) 
I used the dev branch of this project.

**Comment by calebwin** [comment]
Sorry about this. The dev branch is the old version of Emu which you [might be able to get it to compile](https://github.com/calebwin/emu/issues/27). But I'm currently focusing all the time I spend on Emu on the newest version ([crate link](https://crates.io/crates/emu_core)). If you have issues compiling that, please do let me know. Thanks.

**Comment by PerfectStepCoder** [comment]
Ok. So, I have some error while complining emu_macro. Look ar this image, please: 
![image](https://user-images.githubusercontent.com/23447745/79062303-b23ad380-7ca1-11ea-91f6-8721039dff39.png)

**Comment by calebwin** [comment]
Sorry but both `emu_macro` and `em` are part of the older version. The newest version is [`emu_core`](crates.io/crates/emu_core).

**Comment by PerfectStepCoder** [comment]
I see, ok. I am intrested in your project. I will text you late, becouse now it is too late in Seattle.
