### ISSUE TITLE
Support for structs and typechecking?

### ISSUE THREAD

**Issue by SuperFluffy** [calebwin/emu#5]
I wanted to ping you and make you aware of this project having raised quite some interest on reddit. There are two interesting questions, one about potential struct support, and the other about type checking/inference before translation.

Maybe they are of interest to you? See the reddit thread here: https://www.reddit.com/r/rust/comments/bvwvpd/emu_gpu_programming_language_for_rust/

**Comment by calebwin** [comment]
Hi Richard,

Sorry about that- I would really like to write answers to the questions people have and I'll get to doing so as soon as possible.

**Comment by calebwin** [comment]
The only things Emu functions can really accept right now are vectors (technically arrays/pointers) and primitive data (f32 or i32). Simple structures could be accepted with 2 changes.

- A change to the language so you can declare what kind of structs you accept and how to unpackage primitive data from them in the declaration of the Emu function
- A change to the build! macro to generate a function that can accept structs of a certain type and unpackage them into primitive data to send to the Emu function.

(this was x-posted from r/rust)

**Comment by kpp** [comment]
Still having an open issue to track progress would be nice. Issues for structs/vector types/pointers...

**Comment by calebwin** [comment]
Yes, this issue was more of a request for me to respond to some of the question people have about structs as well as typechecking (I think?) so I closed it. But I just opened an issue for discussing structs specifically - https://github.com/calebwin/emu/issues/7.
